spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?useSSL=false
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .html
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  mapper-locations: classpath:io/yg/mapper/*Mapper.xml
  type-aliases-package: io.gjf.entity



server:
  port: 8088
  context-path: /SharedFS
  jsp-servlet:
    init-parameters:
     development: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




